### ISSUE TITLE
blank page with Fruit data using gvisMotionChart

### ISSUE THREAD

**Issue by bkaniskan** [mages/googleVis#78]
Practicing to learn googleVis and unfortunately I am getting blank page. When I used RStudio it is a separate tab not within viewer pane. In base R it is a blank page. I suspect that it might be some setting issues on my end but do not know. Any suggestions how I can fix it?

library(googleVis)
M <- gvisMotionChart(data=Fruits, idvar="Fruit", timevar="Date", chartid="ILoveFruit")
plot(M)

**Comment by mages** [comment]
The motion chart requires Flash to be installed on your computer. You can check this by visiting the CRAN page with googleVis examples: https://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html  Motion charts are at the bottom of the page.

**Comment by vshekharrc** [comment]
Allowing permissions to flash did not solve the problem to me. The page continues to be blank even after this. Any other suggestions to fix this issue, please?

**Comment by vshekharrc** [comment]
> Allowing permissions to flash did not solve the problem to me. The page continues to be blank even after this. Any other suggestions to fix this issue, please?

Okay, I think I got the solution here. The problem was not with the flash settings for me. It was with the parameter , chartid, of the gvisMotionChart. The chartId should be a character string with no spaces in between as in the below line of code:

M = gvisMotionChart(Fruits, idvar = "Fruit", timevar = "Date", chartid = "I_lovemy_fruit")

plot(M)

and not like this:

M = gvisMotionChart(Fruits, idvar = "Fruit", timevar = "Date", chartid = "I love my fruit")

plot(M)

This resolved my issue!!. Hope this helps
